### PR TITLE
replaced pseudo promise obj with js Promise for then chaining

### PR DESCRIPTION
**Pull request by MichaelRando**

### CODE REVIEW

**Comment by Flux159** [comment]
Need to test this change; don't have much time this week, but might be able to next week - also, I see that you changed uhttp to use promises, but not uhttp-server - any reason for that? (libs/uhttp-server is a different codebase with the same public api that is used when requiring in nodejs and uses the same 'fake promises' system)

**Comment by MichaelRando** [comment]
Oh sorry, didn't notice uhttp-server. We're a python backend.

**Comment by Flux159** [comment]
Going to merge this and release a new version 2.0.0-alpha.1 at least until the code for uhttp-server is also rewritten. Sorry its taken so long for this; it fell off the radar for a while.

**Comment by Flux159** [comment]
Updated uhttp-server.js as well, but having issues with some tests for the client side uhttp at the moment - had to update a lot of devDependencies - will try to publish 2.0 tomorrow.

**Comment by Flux159** [comment]
So fixed up the tests - there was an issue with how Promises can only resolve / reject one value. So doing something like

```javascript
new Promise((resolve, reject) => {
  resolve(response, status, xhr);
});
```

Doesn't work - this made me add a details option to the readme: https://github.com/Flux159/uhttp#optionsdetails

Version 2.0 on npm has that fix. I don't think that it should cause many issues if you were only using response, but it would be a breaking change if you were using status or xhr.

Also updated uhttp-server to use Promises.

Thanks for doing this btw! I realized that I wanted to use uhttp with async await and it was impossible to do so without migrating to Promises.

**Pull request merged**
